security:
    # https://symfony.com/doc/current/reference/configuration/security.html#encoders
    encoders:
        App\Domain\Entity\UserInterface:
            algorithm: sodium

    # https://symfony.com/doc/current/security/user_provider.html
    providers:
        entity_provider:
            entity:
                class: App\Domain\Entity\User

    # https://symfony.com/doc/current/security.html#security-role-hierarchy
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/reference/configuration/security.html#firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/v(\d+\.\d+)/login
            stateless: true
            anonymous: true
            # https://symfony.com/doc/current/security/json_login_setup.html
            json_login:
                check_path: jwt_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        public:
            pattern: ^/v(\d+\.\d+)/(confirm|refresh|register|reset|set)
            stateless: true
            anonymous: true
        api:
            pattern: ^/
            stateless: true
            # https://symfony.com/doc/current/security/guard_authentication.html
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # https://symfony.com/doc/current/security/access_control.html
    access_control:
        - { path: ^/v(\d+\.\d+)/(confirm|login|refresh|register|reset|set), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
