version: '3.4'

services:
  db:
    image: mariadb:10.4
    container_name: api_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql:rw

  adminer:
    image: adminer:latest
    container_name: api_adminer
    depends_on:
      - db
    ports:
      - 8081:8080

  php:
    image: php:7.3-fpm-alpine
    container_name: api_php
    build:
      context: .
      target: app_php
    depends_on:
      - db
    volumes:
      - .:/srv/api:rw
      - ./var:/srv/api/var:rw

  nginx:
    image: nginx:1.17-alpine
    container_name: api_nginx
    build:
      context: .
      target: app_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - 8080:80

  redoc:
    image: redocly/redoc:latest
    container_name: api_redoc
    environment:
      - SPEC_URL=http://localhost:8080/openapi.json
    depends_on:
      - nginx
    ports:
      - 8082:80

volumes:
  db-data: {}
